# Generated by Django 4.2.28 on 2026-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_quote',
            field=models.TextField(default='"Technology is the vessel, but storytelling is the destination. I create digital landmarks that bridge the gap between imagination and reality."'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='THE MIND BEHIND', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drone_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='DESIGNED BY ADRIAN', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='THEORY', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tagline',
            field=models.CharField(default='Digital Experiences & Aerial Visuals', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='ACTIVE', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=33.5731, max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=-7.5898, max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
