# Generated by Django 4.2.28 on 2026-02-25
"""
Migration: Add requires_password_change field and create default admin user.
IMPORTANT: INITIAL_ADMIN_EMAIL and INITIAL_ADMIN_PASSWORD environment variables 
must be set before running this migration. No default credentials are provided.
After first login, the admin will be prompted to change their password.
"""

from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
import os


def create_default_admin(apps, schema_editor):
    """
    Create default admin user if no admin exists.
    Requires INITIAL_ADMIN_EMAIL and INITIAL_ADMIN_PASSWORD environment variables.
    """
    CustomUser = apps.get_model('api', 'CustomUser')
    
    # Check if any admin already exists
    if CustomUser.objects.filter(user_type='admin').exists():
        return
    
    # Get credentials from environment - NO DEFAULTS for security
    admin_email = os.environ.get('INITIAL_ADMIN_EMAIL')
    admin_password = os.environ.get('INITIAL_ADMIN_PASSWORD')
    
    # Validate that credentials are provided
    if not admin_email or not admin_password:
        print(f"\n{'='*60}")
        print("ADMIN USER CREATION SKIPPED")
        print(f"{'='*60}")
        print("To create an admin user, set these environment variables:")
        print("  - INITIAL_ADMIN_EMAIL=your-email@example.com")
        print("  - INITIAL_ADMIN_PASSWORD=your-secure-password")
        print("\nThen run: python manage.py migrate")
        print("Or use: python create_superuser.py")
        print(f"{'='*60}\n")
        return
    
    # Validate password strength using Django's password validators
    try:
        validate_password(admin_password)
    except ValidationError as e:
        print(f"\n{'='*60}")
        print("ADMIN USER CREATION FAILED - PASSWORD VALIDATION ERROR")
        print(f"{'='*60}")
        print(f"Password does not meet security requirements:")
        for error in e.messages:
            print(f"  - {error}")
        print("\nPlease set a stronger password and try again.")
        print(f"{'='*60}\n")
        return
    
    # Create the admin user with hashed password
    # Note: We use make_password directly because the historical model doesn't have set_password
    admin = CustomUser.objects.create(
        email=admin_email,
        password=make_password(admin_password),
        user_type='admin',
        is_staff=True,
        is_superuser=True,
        requires_password_change=True,  # Force password change on first login
        auth_provider='email',
        email_notifications=True,
        notify_new_projects=True,
        notify_updates=True,
    )
    
    print(f"\n{'='*60}")
    print("ADMIN USER CREATED SUCCESSFULLY")
    print(f"{'='*60}")
    print(f"   Email: {admin_email}")
    print(f"{'='*60}")
    print("IMPORTANT: Please change your password after first login!")
    print(f"{'='*60}\n")


def reverse_create_default_admin(apps, schema_editor):
    """
    Reverse migration: Remove the default admin if it was created by this migration.
    Only deletes if INITIAL_ADMIN_EMAIL is set - no hardcoded fallbacks.
    """
    CustomUser = apps.get_model('api', 'CustomUser')
    admin_email = os.environ.get('INITIAL_ADMIN_EMAIL')
    if admin_email:
        CustomUser.objects.filter(email=admin_email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email'),
    ]

    operations = [
        # Add the requires_password_change field
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
        # Create the default admin user
        migrations.RunPython(create_default_admin, reverse_create_default_admin),
    ]
