# Generated by Django 4.2.28 on 2026-02-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings_about_quote_sitesettings_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL to your favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to your logo image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='ADRIAN', max_length=100),
        ),
    ]
