# Generated by Django 4.2.28 on 2026-02-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
