# Generated by Django 4.2.28 on 2026-02-28 04:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_visitor_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Image Upload', 'verbose_name_plural': 'Image Uploads'},
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=api.models.get_image_upload_path),
        ),
    ]
