# Generated by Django 4.2.28 on 2026-03-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_mediaupload_delete_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True,
                        help_text="CSRF token for OAuth flow",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        help_text="Nonce for ID token validation (OpenID Connect)",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("google", "Google"),
                            ("microsoft", "Microsoft"),
                        ],
                        help_text="OAuth provider identifier",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this state token expires (15 min)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Secret refresh token value",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this refresh token expires"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was revoked (null = still valid)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
            },
        ),
        migrations.CreateModel(
            name="VisitorConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SESSION_KEY",
                    models.CharField(
                        db_index=True,
                        help_text="Unique session identifier",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "IP_ADDRESS",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of visitor (not anonymized at consent time)",
                        null=True,
                    ),
                ),
                (
                    "CONSENT_GIVEN",
                    models.BooleanField(
                        default=False, help_text="Whether visitor consented to tracking"
                    ),
                ),
                (
                    "CONSENT_VERSION",
                    models.CharField(
                        default="1.0",
                        help_text="Version of privacy policy accepted",
                        max_length=10,
                    ),
                ),
                ("CREATED_AT", models.DateTimeField(auto_now_add=True)),
                (
                    "EXPIRES_AT",
                    models.DateTimeField(
                        help_text="When consent expires (usually 90 days from creation)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Consent",
                "verbose_name_plural": "Visitor Consents",
            },
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="visitor",
            name="anonymized_ip",
            field=models.GenericIPAddressField(
                blank=True,
                db_index=True,
                help_text="IP with last octet anonymized (e.g., 192.168.1.0)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="will_delete_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this record will auto-delete (90 days after creation)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="is_unique",
            field=models.BooleanField(
                default=True, help_text="Whether this is a unique visitor"
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="path",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Request path",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="referrer",
            field=models.URLField(
                blank=True, help_text="HTTP referrer", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Django session key for this visitor",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="Browser user agent string", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="visit_time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["-visit_time"], name="api_visitor_visit_t_c80462_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["session_key"], name="api_visitor_session_e136ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["will_delete_at"], name="api_visitor_will_de_f29689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorconsent",
            index=models.Index(
                fields=["SESSION_KEY"], name="api_visitor_SESSION_ea88a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorconsent",
            index=models.Index(
                fields=["EXPIRES_AT"], name="api_visitor_EXPIRES_17ed20_idx"
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_token",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="oauthstate",
            index=models.Index(
                fields=["state", "provider"], name="api_oauthst_state_efe34e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthstate",
            index=models.Index(
                fields=["expires_at"], name="api_oauthst_expires_882de1_idx"
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="consent_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to consent record at time of visit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.visitorconsent",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["token"], name="api_refresh_token_fbb98a_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expires_at"], name="api_refresh_expires_661feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user"], name="api_refresh_user_id_0cac9a_idx"),
        ),
    ]
