# Generated by Django 4.2.28 on 2026-03-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_oauthstate_refreshtoken_visitorconsent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("user",),
                name="unique_active_refresh_token_per_user",
            ),
        ),
    ]
