# Generated by Django 4.2.28 on 2026-03-08 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_refreshtoken_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("brute_force", "Brute Force Attack"),
                            ("unusual_location", "Login from Unusual Location"),
                            ("impossible_travel", "Impossible Travel"),
                            ("mass_api_requests", "Mass API Requests"),
                            ("data_exfiltration", "Data Exfiltration"),
                            ("privilege_escalation", "Privilege Escalation"),
                            ("malware_detected", "Malware Detected"),
                            ("custom", "Custom Alert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(help_text="Alert title", max_length=255)),
                ("description", models.TextField(help_text="Detailed description")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evidence data (IP addresses, IPs, counts, etc)",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, help_text="What was done (e.g., account locked)"
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Alert",
                "verbose_name_plural": "Security Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_securit_status_c7473e_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="api_securit_severit_61c003_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_securit_user_id_9296c9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Successful Login"),
                            ("failed", "Failed Login"),
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_locked", "Account Locked"),
                            ("mfa_required", "MFA Required"),
                        ],
                        default="failed",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Source IP address"),
                ),
                ("user_agent", models.TextField(help_text="Full user agent string")),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Device type: desktop, mobile, tablet",
                        max_length=50,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Browser name and version", max_length=100
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="Operating system", max_length=100
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country based on IP geolocation",
                        max_length=100,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City based on IP geolocation",
                        max_length=100,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "failed_attempt_after_success",
                    models.BooleanField(
                        default=False,
                        help_text="True if this failed login came shortly after a successful one",
                    ),
                ),
                (
                    "unusual_location",
                    models.BooleanField(
                        default=False,
                        help_text="True if login is from unusual location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who attempted login (NULL if user not found)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Activity",
                "verbose_name_plural": "Login Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_loginac_user_id_34ccef_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="api_loginac_ip_addr_4d3368_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_loginac_status_765549_idx",
                    ),
                    models.Index(
                        fields=["country", "-created_at"],
                        name="api_loginac_country_871f69_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("password_change", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("email_change", "Email Changed"),
                            ("profile_update", "Profile Updated"),
                            ("profile_picture_upload", "Profile Picture Uploaded"),
                            ("api_request", "API Request"),
                            ("data_create", "Data Created"),
                            ("data_update", "Data Updated"),
                            ("data_delete", "Data Deleted"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_type_changed", "User Type Changed"),
                            ("security_alert", "Security Alert"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("session_revoked", "Session Revoked"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of object affected (User, Profile, etc)",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the affected object", null=True
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of changes: {field: (old_value, new_value)}",
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_activit_user_id_29f0f8_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="api_activit_action_35dd86_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="api_activit_created_011954_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="api_activit_object__1d3de7_idx",
                    ),
                ],
            },
        ),
    ]
