# Generated by Django 4.2.28 on 2026-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("social_login", "Social/OAuth Login"),
                    ("new_user_registration", "New User Registration"),
                    ("password_change", "Password Changed"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Changed"),
                    ("profile_update", "Profile Updated"),
                    ("profile_picture_upload", "Profile Picture Uploaded"),
                    ("api_request", "API Request"),
                    ("data_create", "Data Created"),
                    ("data_update", "Data Updated"),
                    ("data_delete", "Data Deleted"),
                    ("user_created", "User Created"),
                    ("user_updated", "User Updated"),
                    ("user_deleted", "User Deleted"),
                    ("user_type_changed", "User Type Changed"),
                    ("security_alert", "Security Alert"),
                    ("mfa_enabled", "MFA Enabled"),
                    ("mfa_disabled", "MFA Disabled"),
                    ("session_revoked", "Session Revoked"),
                ],
                max_length=30,
            ),
        ),
    ]
