# Generated by Django 4.2.28 on 2026-03-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_add_social_login_action_choices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="visitorconsent",
            name="api_visitor_SESSION_ea88a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="visitorconsent",
            name="api_visitor_EXPIRES_17ed20_idx",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="CONSENT_GIVEN",
            new_name="consent_given",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="CONSENT_VERSION",
            new_name="consent_version",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="CREATED_AT",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="EXPIRES_AT",
            new_name="expires_at",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="IP_ADDRESS",
            new_name="ip_address",
        ),
        migrations.RenameField(
            model_name="visitorconsent",
            old_name="SESSION_KEY",
            new_name="session_key",
        ),
        migrations.AddIndex(
            model_name="visitorconsent",
            index=models.Index(
                fields=["session_key"], name="api_visitor_session_8da3ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorconsent",
            index=models.Index(
                fields=["expires_at"], name="api_visitor_expires_330f94_idx"
            ),
        ),
    ]
