# Generated by Django 4.2.28 on 2026-03-12 08:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_visitorconsent_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaupload",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=api.models.get_media_upload_path
            ),
        ),
    ]
