[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "gunicorn portfolio.wsgi:application -c /app/gunicorn.conf.py"
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
