# Generated by Django 4.2.28 on 2026-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='likes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='likes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
