# Generated by Django 4.2.28 on 2026-02-24 01:29

from django.db import migrations


def populate_initial_likes_count(apps, schema_editor):
    """Populate initial likes count from existing Like records"""
    Project = apps.get_model('projects', 'Project')
    MediaItem = apps.get_model('projects', 'MediaItem')
    Like = apps.get_model('interactions', 'Like')

    # Populate project likes count
    for project in Project.objects.all():
        project.likes_count = Like.objects.filter(project=project).count()
        project.save(update_fields=['likes_count'])

    # Populate media item likes count
    for media_item in MediaItem.objects.all():
        media_item.likes_count = Like.objects.filter(media=media_item).count()
        media_item.save(update_fields=['likes_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_mediaitem_likes_count_project_likes_count'),
        ('interactions', '0001_initial'),  # Add dependency on interactions app
    ]

    operations = [
        migrations.RunPython(populate_initial_likes_count, reverse_code=migrations.RunPython.noop),
    ]
