# Generated by Django 4.2.28 on 2026-02-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_populate_initial_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
