# Generated by Django 4.2.28 on 2026-02-28 02:40

from django.db import migrations, models


def migrate_media_urls_to_file_field(apps, schema_editor):
    """
    Migrate existing URL data to file field before removing the URL field.
    This preserves any existing URL references in the database.
    """
    MediaItem = apps.get_model('projects', 'MediaItem')
    for item in MediaItem.objects.filter(url__isnull=False).exclude(url=''):
        # Store the URL as a reference in the file field
        # This preserves the URL data before the url field is removed
        item.file = item.url
        item.save(update_fields=['file'])
        print(f"Migrated MediaItem {item.id}: URL '{item.url}' -> file field")


def reverse_migrate_file_to_url_field(apps, schema_editor):
    """
    Reverse migration: restore URL field from file field.
    """
    MediaItem = apps.get_model('projects', 'MediaItem')
    for item in MediaItem.objects.filter(file__isnull=False).exclude(file=''):
        # Restore the URL from the file field
        item.url = str(item.file)
        item.save(update_fields=['url'])
        print(f"Reversed MediaItem {item.id}: File '{item.file}' -> URL field")


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_is_featured_project_featured'),
    ]

    operations = [
        # First, add the file field to receive the URL data
        migrations.AddField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, help_text='Upload high-resolution image or video file (max 50MB)', null=True, upload_to='project_media/%Y/%m/'),
        ),
        # Migrate existing URL data to file field
        migrations.RunPython(
            migrate_media_urls_to_file_field,
            reverse_migrate_file_to_url_field,
        ),
        # Now safe to remove the URL field
        migrations.RemoveField(
            model_name='mediaitem',
            name='url',
        ),
        # Update thumbnail field
        migrations.AlterField(
            model_name='mediaitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail for videos', null=True, upload_to='project_media/thumbnails/%Y/%m/'),
        ),
    ]
