# Generated by Django 4.2.28 on 2026-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_mediaitem_url_mediaitem_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_registration',
            field=models.BooleanField(default=True, help_text='Show registration button on project detail page'),
        ),
    ]
