# Generated by Django 4.2.28 on 2026-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_show_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Développement', 'Développement'), ('Drone', 'Drone'), ('Mélangé', 'Mélangé')], default='Développement', max_length=20),
        ),
    ]
