# Generated by Django 4.2.28 on 2026-02-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='Your Name. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='designer_name',
            field=models.CharField(blank=True, default='ADRIAN', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
    ]
