# Generated by Django 4.2.28 on 2026-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_home_page_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_quote',
            field=models.TextField(default='"Technology is the vessel, but storytelling is the destination. I create digital landmarks that bridge the gap between imagination and reality."'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='THE MIND BEHIND', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drone_image',
            field=models.URLField(blank=True, help_text='Drone/work image URL for about section', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_about_label',
            field=models.CharField(default='About', help_text='Label for About navigation link', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_contact_label',
            field=models.CharField(default='Contact', help_text='Label for Contact navigation link', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_work_label',
            field=models.CharField(default='Work', help_text='Label for Work navigation link', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Profile image URL for about section', max_length=500, null=True),
        ),
    ]
