# Generated by Django 4.2.28 on 2026-02-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_about_quote_sitesettings_about_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='CREATIVE DEVELOPER', max_length=100),
        ),
    ]
