# Generated by Django 4.2.28 on 2026-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_sitesettings_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#ec4899', help_text='Accent color hex code (e.g., #ec4899)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#0a0a0a', help_text='Background color hex code (e.g., #0a0a0a)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cursor_size',
            field=models.IntegerField(default=20, help_text='Cursor size in pixels (10-50)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cursor_theme',
            field=models.CharField(default='default', help_text='Cursor theme (default, neon, minimal, custom)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_cursor_color',
            field=models.CharField(default='#6366f1', help_text='Custom cursor color hex code (only applicable if cursor theme is custom)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#6366f1', help_text='Primary color hex code (e.g., #6366f1)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', help_text='Secondary color hex code (e.g., #8b5cf6)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='designer_name',
            field=models.CharField(blank=True, default='WAEL', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='WAEL', max_length=100),
        ),
    ]
