# Generated by Django 4.2.28 on 2026-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='drone_video',
            field=models.URLField(blank=True, help_text='Drone/work video URL for about section (will be used instead of image if provided)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='drone_video_url',
            field=models.URLField(blank=True, help_text='Drone/work video URL for about section', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background_video',
            field=models.URLField(blank=True, help_text='Footer background video URL (will be used instead of solid background if provided)', max_length=500, null=True),
        ),
    ]
