# Generated by Django 4.2.28 on 2026-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_drone_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='drone_video',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='drone_video_url',
            field=models.URLField(blank=True, help_text='Drone/work video URL for about section (will be used instead of image if provided)', max_length=500, null=True),
        ),
    ]
