# Generated by Django 4.2.28 on 2026-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_remove_sitesettings_drone_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="facebook_app_secret",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="google_client_secret",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="_email_host_password",
            field=models.CharField(
                blank=True, db_column="email_host_password", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="_facebook_app_secret",
            field=models.CharField(
                blank=True, db_column="facebook_app_secret", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="_google_client_secret",
            field=models.CharField(
                blank=True, db_column="google_client_secret", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_button_text",
            field=models.CharField(default="Envoyer le Message", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_placeholder_email",
            field=models.CharField(default="nom@email.com", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_placeholder_message",
            field=models.CharField(
                default="Parlez-moi de votre vision...", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_placeholder_name",
            field=models.CharField(default="Votre Nom", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_placeholder_subject",
            field=models.CharField(default="Sujet", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_subtitle",
            field=models.TextField(
                default="Que vous ayez besoin d'un ingénieur full-stack ou d'un cinéaste drone, je suis prêt pour le prochain défi."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_title",
            field=models.CharField(default="Créons Ensemble", max_length=100),
        ),
    ]
