# Generated by Django 4.2.28 on 2026-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_remove_sitesettings_email_host_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cursor_enabled_mobile",
            field=models.BooleanField(
                default=False, help_text="Enable custom cursor on mobile/touch devices"
            ),
        ),
    ]
