# Generated by Django 4.2.28 on 2026-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvlanguage',
            name='percentage',
            field=models.IntegerField(default=50, help_text='Language proficiency percentage (0-100)'),
        ),
    ]
