# Generated by Django 4.2.28 on 2026-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvlanguage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvskill',
            name='category',
            field=models.CharField(default='technical', max_length=50),
        ),
    ]
