# Generated by Django 4.2.28 on 2026-03-07 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_alter_cvskill_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvlanguage",
            name="percentage",
            field=models.IntegerField(
                default=50,
                help_text="Language proficiency percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cvskill",
            name="percentage",
            field=models.IntegerField(
                default=80,
                help_text="Skill percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
